version: 0.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
platform: Any CPU
clone_depth: 5
before_build:
- ps: >-
    git submodule update --init --recursive

    dotnet restore
build:
  project: ADTConvert2.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_core_console: true
  parallel: true
  verbosity: minimal